# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e084951856067cfef78baed6c8d88f264d4760d51826448c215bde0bf625f7797db188b84abec91708a9a158bb5adafe9a0b422b59b38f0b2b54fc8f01a82243

test:
  secret_key_base: a2b25e378d41167d71d37895f0cc18a632ffe725e5daaaffe3bdd6439b89afe4069bc49fd031257c2d378fa03257b05844641c875ef41220baf9c08ce2e82144

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
